# Generated by Django 3.1.2 on 2020-11-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=128, unique=True)),
                ('image1', models.ImageField(null=True, upload_to='doubleimage/image1')),
                ('title2', models.CharField(max_length=128, unique=True)),
                ('image2', models.ImageField(null=True, upload_to='doubleimage/image2')),
            ],
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
