# Generated by Django 3.1.2 on 2020-11-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20201126_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubleimages',
            name='title1',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='doubleimages',
            name='title2',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
