# Generated by Django 3.1.2 on 2020-12-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20201213_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doubleimages',
            old_name='referenceimg_image',
            new_name='ReferenceImg_image',
        ),
        migrations.RenameField(
            model_name='doubleimages',
            old_name='referenceimg_title',
            new_name='ReferenceImg_title',
        ),
        migrations.RenameField(
            model_name='doubleimages',
            old_name='testimg_image',
            new_name='TestImg_image',
        ),
        migrations.RenameField(
            model_name='doubleimages',
            old_name='testimg_title',
            new_name='TestImg_title',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='title',
            new_name='Title',
        ),
    ]
