# Generated by Django 3.1.2 on 2021-04-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20201213_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='Title',
        ),
    ]
