# Generated by Django 3.1.2 on 2021-04-01 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_images_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubleimages',
            name='ReferenceImg_title',
        ),
        migrations.RemoveField(
            model_name='doubleimages',
            name='TestImg_title',
        ),
    ]
