# Generated by Django 3.1.2 on 2021-04-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20210401_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleImagesResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestImg_image', models.ImageField(null=True, upload_to='doubleimageResult/testimg_image')),
                ('ReferenceImg_image', models.ImageField(null=True, upload_to='doubleimageResult/referenceimg_image')),
                ('result', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagesResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.ImageField(null=True, upload_to='imagesResult')),
                ('ImagesRef', models.ImageField(null=True, upload_to='imagesResult')),
                ('result', models.CharField(max_length=16, null=True)),
            ],
        ),
    ]
