# Generated by Django 3.1.2 on 2021-04-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_doubleimagesresult_imagesresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubleimagesresult',
            name='score_info',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
