# Generated by Django 3.1.2 on 2021-04-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_doubleimagesresult_score_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubleimagesresult',
            name='user',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
