# Generated by Django 3.1.2 on 2021-04-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_doubleimagesresult_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doubleimagesresult',
            old_name='user',
            new_name='user_name',
        ),
    ]
