# Generated by Django 3.1.2 on 2021-04-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20210408_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesresult',
            name='user_name',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
